version: '3.7'

services:
  web:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev

  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: postgres2