version: '3.7'

services:
  web:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod  

  nginx:
    build: ./nginx
    ports:
      - "8080:80" 
    depends_on:
      - web

  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
    env_file:
      - ./.env.db